insert into SHIP_CLASS (
INITIATIVE, SHIP_TYPE, AMOUNT, SHIP_SIZE, SPEED, WEAPON_TYPE, WEAPON_RANGE, START_HEALTH)
values(1, 'Submarine', 1, 2, 4, 2, 20, 1);

insert into SHIP_CLASS (
INITIATIVE, SHIP_TYPE, AMOUNT, SHIP_SIZE, SPEED, WEAPON_TYPE, WEAPON_RANGE, START_HEALTH)
values(2, 'Frigate', 2, 2, 8, 3, 4, 2);

insert into SHIP_CLASS (
INITIATIVE, SHIP_TYPE, AMOUNT, SHIP_SIZE, SPEED, WEAPON_TYPE, WEAPON_RANGE, START_HEALTH)
values(3, 'Carrier', 1, 4, 3, 1, 30, 3);

insert into SHIP_CLASS (
INITIATIVE, SHIP_TYPE, AMOUNT, SHIP_SIZE, SPEED, WEAPON_TYPE, WEAPON_RANGE, START_HEALTH)
values(4, 'Minelayer', 1, 2, 6, 4, 3, 2);

insert into SHIP_CLASS (
INITIATIVE, SHIP_TYPE, AMOUNT, SHIP_SIZE, SPEED, WEAPON_TYPE, WEAPON_RANGE, START_HEALTH)
values(5, 'Destroyer', 2, 3, 6, 0, 8, 2);

insert into SHIP_CLASS (
INITIATIVE, SHIP_TYPE, AMOUNT, SHIP_SIZE, SPEED, WEAPON_TYPE, WEAPON_RANGE, START_HEALTH)
values(6, 'Cruiser', 1, 4, 4, 0, 12, 3);