insert into SHIP_CLASS (
INITIATIVE, SHIP_TYPE, AMOUNT, SHIP_SIZE, SPEED, WEAPON_TYPE, WEAPON_RANGE, ORDNANCE, START_HEALTH)
values(1, 'Submarine', 2, 2, 4, 2, 20, 3, 1);

insert into SHIP_CLASS (
INITIATIVE, SHIP_TYPE, AMOUNT, SHIP_SIZE, SPEED, WEAPON_TYPE, WEAPON_RANGE, ORDNANCE, START_HEALTH)
values(2, 'Frigate', 3, 2, 8, 3, 4, 6, 2);

insert into SHIP_CLASS (
INITIATIVE, SHIP_TYPE, AMOUNT, SHIP_SIZE, SPEED, WEAPON_TYPE, WEAPON_RANGE, ORDNANCE, START_HEALTH)
values(3, 'Carrier', 1, 4, 3, 1, 30, 2, 3);

insert into SHIP_CLASS (
INITIATIVE, SHIP_TYPE, AMOUNT, SHIP_SIZE, SPEED, WEAPON_TYPE, WEAPON_RANGE, ORDNANCE, START_HEALTH)
values(4, 'Destroyer', 4, 3, 6, 0, 8, 10, 2);

insert into SHIP_CLASS (
INITIATIVE, SHIP_TYPE, AMOUNT, SHIP_SIZE, SPEED, WEAPON_TYPE, WEAPON_RANGE, ORDNANCE, START_HEALTH)
values(5, 'Cruiser', 2, 4, 4, 0, 12, 15, 3);